<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- For publishing to sonatype / central maven repo -->
    <!--
    <parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>7</version>
    </parent>
    -->

    <groupId>net.finmath</groupId>
    <artifactId>finmath-smart-derivative-contract</artifactId>
    <version>1.2.14-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>finmath-smart-derivative-contract</name>
    <description>
        Project to support the implementation a of smart derivative contract.
    </description>
    <url>https://www.finmath.net/finmath-smart-derivative-contract</url>
	<modules>
		<module>core</module>
        <module>app</module>
    </modules>

	<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <src.main.java.dir>src/main/java</src.main.java.dir>
        <src.test.java.dir>src/test/java</src.test.java.dir>
        <java.version>17</java.version>
        <nv-websocket-client.version>2.14</nv-websocket-client.version>
        <moneta.version>1.4.2</moneta.version>
        <jcommon.version>1.0.24</jcommon.version>
        <springdoc-openapi-ui.version>2.2.0</springdoc-openapi-ui.version>
        <jackson-databind-nullable.version>0.2.6</jackson-databind-nullable.version>
        <commons-cli.version>1.5.0</commons-cli.version>
        <spring-boot-dependencies.version>3.2.10</spring-boot-dependencies.version>
        <finmath-lib.version>6.0.19</finmath-lib.version>
        <finmath-lib-plot-extensions.version>0.5.3</finmath-lib-plot-extensions.version>
        <spring-statemachine.version>3.2.0</spring-statemachine.version>
        <!-- maven plugins -->
        <maven.site-plugin.version>4.0.0-M13</maven.site-plugin.version>
        <maven-scm-publish-plugin.version>3.2.1</maven-scm-publish-plugin.version>
        <maven-project-info-reports-plugin.version>3.4.2</maven-project-info-reports-plugin.version>
        <maven-checkstyle-plugin.version>3.2.1</maven-checkstyle-plugin.version>
        <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
        <maven-surefire-plugin.version>3.0.0</maven-surefire-plugin.version>
        <maven-source-plugin.version>3.2.1</maven-source-plugin.version>
        <maven-javadoc-plugin.version>3.5.0</maven-javadoc-plugin.version>
        <maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
        <maven-central-publishing-maven.version>0.8.0</maven-central-publishing-maven.version>
        <versions-maven-plugin.version>2.15.0</versions-maven-plugin.version>
        <spring-boot-maven-plugin.version>3.0.5</spring-boot-maven-plugin.version>
        <maven-enforcer-plugin.version>3.2.1</maven-enforcer-plugin.version>
        <maven-dependency-plugin.version>3.5.0</maven-dependency-plugin.version>
        <maven-resources-plugin.version>3.3.1</maven-resources-plugin.version>
        <openapi-generator-maven-plugin.version>6.4.0</openapi-generator-maven-plugin.version>
        <jib-maven-plugin.version>3.3.1</jib-maven-plugin.version>
        <wagon-ssh.version>3.5.3</wagon-ssh.version>
        <doxia-sitetools.version>2.0.0-M6</doxia-sitetools.version>
        <doxia-skin-model.version>2.0.0-M6</doxia-skin-model.version>
        <doxia-module-markdown.version>2.0.0-M6</doxia-module-markdown.version>
        <git-commit-id-maven-plugin.version>5.0.0</git-commit-id-maven-plugin.version>
        <httpcore.version>5.3</httpcore.version>
        <frontend-maven-plugin.version>1.15.0</frontend-maven-plugin.version>
        <exec-maven-plugin.version>3.1.0</exec-maven-plugin.version>
    </properties>

    <developers>
        <developer>
            <id>fries</id>
            <name>Christian Fries</name>
            <email>email@christian-fries.de</email>
            <url>http://www.christian-fries.de</url>
            <timezone>1</timezone>
        </developer>
        <developer>
            <id>pekola</id>
            <name>Peter Kohl-Landgraf</name>
            <timezone>1</timezone>
        </developer>
        <developer>
            <id>delre</id>
            <name>Luca Del Re</name>
            <timezone>1</timezone>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>




    <profiles>
        <profile>
            <id>i-need-node</id>
            <activation>
                <property>
                    <name>iNeedNode</name>
                    <value>true</value>
                </property>
            </activation>
            <properties>
                <node.version>v18.15.0</node.version>
                <versions-maven-plugin.version>2.15.0</versions-maven-plugin.version>
                <frontend-maven-plugin.version>1.12.1</frontend-maven-plugin.version>
                <maven-enforcer-plugin.version>3.2.1</maven-enforcer-plugin.version>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>com.github.eirslett</groupId>
                    <artifactId>frontend-maven-plugin</artifactId>
                    <version>${frontend-maven-plugin.version}</version>
                </dependency>
                <dependency>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${maven-enforcer-plugin.version}</version>
                </dependency>
                <dependency>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>${versions-maven-plugin.version}</version>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-enforcer-plugin</artifactId>
                        <version>${maven-enforcer-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>enforce-maven</id>
                                <goals>
                                    <goal>enforce</goal>
                                </goals>
                                <configuration>
                                    <rules>
                                        <requireMavenVersion>
                                            <version>[3.6.0,)</version>
                                        </requireMavenVersion>
                                    </rules>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>com.github.eirslett</groupId>
                        <artifactId>frontend-maven-plugin</artifactId>
                        <version>${frontend-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>install node and npm</id>
                                <goals>
                                    <goal>install-node-and-npm</goal>
                                </goals>
                                <phase>generate-resources</phase>
                            </execution>
                            <execution>
                                <id>install angular and other dependencies</id>
                                <goals>
                                    <goal>npm</goal>
                                </goals>
                                <phase>generate-resources</phase>
                                <configuration>
                                    <arguments>install</arguments>
                                </configuration>
                            </execution>
                        </executions>
                        <configuration>
                            <nodeVersion>${node.version}</nodeVersion>
                            <workingDirectory>src/main/frontend</workingDirectory>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>i-have-node</id>
            <activation>
                <property>
                    <name>iHaveNode</name>
                    <value>true</value>
                </property>
            </activation>
            <properties>
                <node.version>v18.15.0</node.version>
                <versions-maven-plugin.version>2.15.0</versions-maven-plugin.version>
                <exec-maven-plugin.version>3.1.0</exec-maven-plugin.version>
                <maven-enforcer-plugin.version>3.2.1</maven-enforcer-plugin.version>
            </properties>
            <dependencies>
                <dependency>
                    <artifactId>exec-maven-plugin</artifactId>
                    <groupId>org.codehaus.mojo</groupId>
                    <version>${exec-maven-plugin.version}</version>
                </dependency>
                <dependency>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${maven-enforcer-plugin.version}</version>
                </dependency>
                <dependency>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>${versions-maven-plugin.version}</version>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-enforcer-plugin</artifactId>
                        <version>${maven-enforcer-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>enforce-maven</id>
                                <goals>
                                    <goal>enforce</goal>
                                </goals>
                                <configuration>
                                    <rules>
                                        <requireMavenVersion>
                                            <version>[3.6.0,)</version>
                                        </requireMavenVersion>
                                    </rules>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <artifactId>exec-maven-plugin</artifactId>
                        <groupId>org.codehaus.mojo</groupId>
                        <version>${exec-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>install-angular-and-other-dependencies</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>npm</executable>
                                    <commandlineArgs>install</commandlineArgs>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>no-tests</id>
            <properties>
                <maven.test.skip>true</maven.test.skip>
            </properties>
        </profile>
    </profiles>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/finmath/finmath-lib/issues</url>
    </issueManagement>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven-javadoc-plugin.version}</version>
                <reportSets>
                    <reportSet><!-- by default, id = "default" -->
                        <reports><!-- select non-aggregate reports -->
                            <report>javadoc</report>
                            <!-- <report>test-javadoc</report> -->
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>${maven-project-info-reports-plugin.version}</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>index</report>
                            <report>summary</report>
                            <report>scm</report>
                            <report>distribution-management</report>
                            <report>dependency-info</report>
                            <report>dependencies</report>
                            <report>issue-management</report>
                            <report>ci-management</report>
                            <report>licenses</report>
                            <report>team</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>

    <distributionManagement>
        <!--site for mvn site -->
        <site>
            <id>github</id>
            <url>scm:git:https://github.com/finmath/finmath-smart-derivative-contract.git</url>
        </site>
        <!-- We need to deploy releases to maven central!
        <repository>
            <id>gitlab</id>
            <url>https://gitlab.com/api/v4/projects/33978063/packages/maven</url>
        </repository>
        <snapshotRepository>
            <id>gitlab</id>
            <url>https://gitlab.com/api/v4/projects/33978063/packages/maven</url>
        </snapshotRepository>
        -->
    </distributionManagement>

    <scm>
        <url>https://github.com/finmath/finmath-smart-derivative-contract</url>
        <connection>scm:git:https://github.com/finmath/finmath-smart-derivative-contract.git</connection>
        <developerConnection>scm:git:https://github.com/finmath/finmath-smart-derivative-contract.git
        </developerConnection>
        <tag>HEAD</tag>
    </scm>

</project>
