data:
  sdc:
    users:
      - username: user1
        password: password1
        role: USER_ONE
      - username: user2
        password: password2
        role: USER_TWO

# example to setup SSL

#server:
#  ssl:
#    key-store: config/finmath.p12
#    key-store-password: password
#    key-store-type: pkcs12
#  port: 8443
