name: frontend - finmath smart derivative contract

on: [ push ]

jobs:
  test:
    name: Playwright Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: install playwright dependencies
        run: npx -y playwright@1.42.0 install --with-deps
      - name: build maven
        run: mvn -B clean package -DskipTests
      - name: check files, if target is there
        run: ls ./target/
      - name: start app
        run: java -jar ./target/finmath-smart-derivative-contract-*-SNAPSHOT.jar &
      - name: wait
        run: sleep 20
      - name: Build with Maven
        run: mvn -B test -Dgroups="playwrightTests"
