name: finmath smart derivative contract

#trigg
#only push new SNAPSHOTS from develop
on:
  push:
    branches:
      - develop

jobs:
  bCP1ld:
    name: SNAPSHOT, build and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: upload SNAPSHOT to GitLab
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          PRIVATE_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
        run: mvn -s github_SNAPSHOT_settings.xml clean install deploy